import React from 'react';
import { Spinner } from './Spinner';
import { AspectRatio, ImageMetadata } from '../types';

interface ImageDisplayProps {
  imageUrl: string | null;
  isLoading: boolean;
  aspectRatio: AspectRatio;
  metadata: ImageMetadata | null;
}

const GalleryIcon: React.FC<{ className?: string }> = ({ className }) => (
  <svg xmlns="http://www.w3.org/2000/svg" className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
    <rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect>
    <circle cx="8.5" cy="8.5" r="1.5"></circle>
    <polyline points="21 15 16 10 5 21"></polyline>
  </svg>
);

const DownloadIcon: React.FC<{ className?: string }> = ({ className }) => (
    <svg xmlns="http://www.w3.org/2000/svg" className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
        <polyline points="7 10 12 15 17 10"></polyline>
        <line x1="12" y1="15" x2="12" y2="3"></line>
    </svg>
);


export const ImageDisplay: React.FC<ImageDisplayProps> = ({ imageUrl, isLoading, aspectRatio, metadata }) => {
  const getAspectRatioClass = (ratio: AspectRatio) => {
    switch (ratio) {
      case '16:9': return 'aspect-video';
      case '9:16': return 'aspect-[9/16]';
      case '4:3': return 'aspect-4/3';
      case '3:4': return 'aspect-[3/4]';
      case '1:1':
      default:
        return 'aspect-square';
    }
  };

  return (
    <div className="w-full max-w-3xl mx-auto flex flex-col gap-4">
        <div className={`relative w-full bg-slate-800/50 rounded-xl shadow-lg flex items-center justify-center border-2 border-dashed border-slate-700 transition-all duration-300 ${getAspectRatioClass(aspectRatio)}`}>
        {isLoading && <Spinner />}
        {!isLoading && !imageUrl && (
            <div className="text-center text-slate-500 p-8">
                <GalleryIcon className="w-24 h-24 mx-auto mb-4 opacity-50"/>
                <h3 className="text-xl font-semibold">Your generated image will appear here</h3>
                <p className="mt-1">Enter a prompt below and click 'Generate' to begin.</p>
            </div>
        )}
        {!isLoading && imageUrl && (
            <>
            <img
                src={imageUrl}
                alt="Generated by AI"
                className="object-contain w-full h-full rounded-xl"
            />
            <a
                href={imageUrl}
                download="ai-generated-image.png"
                className="absolute top-4 right-4 bg-slate-900/50 backdrop-blur-sm text-slate-200 p-3 rounded-full hover:bg-teal-500/50 hover:text-white transition-all duration-200 shadow-lg"
                title="Download Image"
            >
                <DownloadIcon className="w-6 h-6" />
            </a>
            </>
        )}
        </div>
        {!isLoading && metadata && (
            <div className="bg-slate-800/50 p-3 rounded-xl border border-slate-700/50 flex justify-around text-center text-sm text-slate-400">
                <div className="px-2">
                    <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-500 mb-1">Resolution</h4>
                    <p className="font-mono text-base text-slate-300">{metadata.resolution}</p>
                </div>
                <div className="px-2">
                    <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-500 mb-1">Aspect Ratio</h4>
                    <p className="font-mono text-base text-slate-300">{metadata.ratio}</p>
                </div>
                <div className="px-2">
                    <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-500 mb-1">Size</h4>
                    <p className="font-mono text-base text-slate-300">{metadata.size}</p>
                </div>
            </div>
        )}
    </div>
  );
};
